# Generated by Django 3.2.3 on 2021-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='tutor',
        ),
        migrations.AddField(
            model_name='role',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
