# Generated by Django 3.2.3 on 2021-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_role_tutee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requesttutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(blank=True, max_length=100, null=True)),
                ('tutee', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('dates', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
