# Generated by Django 3.2.3 on 2021-07-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_accept_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('tuteebool', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('encryption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
