# Generated by Django 3.2.3 on 2021-07-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=10000, null=True)),
                ('answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer1', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer2', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer3', models.CharField(blank=True, max_length=10000, null=True)),
                ('question2', models.CharField(blank=True, max_length=10000, null=True)),
                ('answer2', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer4', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer5', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer6', models.CharField(blank=True, max_length=10000, null=True)),
                ('question3', models.CharField(blank=True, max_length=10000, null=True)),
                ('answer3', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer7', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer8', models.CharField(blank=True, max_length=10000, null=True)),
                ('fakeanswer9', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
